### ISSUE TITLE
Error: No available configurations for the given pixel format

### ISSUE THREAD

**Issue by DroWnThePoor** [Rafostar/clapper#119]
I'm on Ubuntu 18.04(Gnome) with version 3 installed via Flatpak, and I'm getting this message in terminal:

```
Gsk-Message: 02:30:41.978: Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkX11Toplevel': No available configurations for the given pixel format

(com.github.rafostar.Clapper:2): Clapper-CRITICAL **: 02:30:41.998: No available configurations for the given pixel format
```

That's just while running it.
I attempt to open a local .mp4 and it returns:

```
(com.github.rafostar.Clapper:2): Gtk-WARNING **: 02:35:09.578: Couldn't unexport handle for GdkX11Toplevel surface, unsupported windowing system
(com.github.rafostar.Clapper:2): Clapper-CRITICAL **: 02:35:09.612: Failed to play
```

Nothing happens visually from the GUI, but there have also been some total crashes when trying to open local or URL's.

Also using Nvidia's drivers on a Quadro GPU, and I have two displays running that are different resolutions and aspect ratios.

**Comment by Rafostar** [comment]
This seems like a GTK4 issue. Please try if you are able to run:
```sh
flatpak run --command=sh com.github.rafostar.Clapper
gtk4-demo
```
Once app opens check if you got any of your previous errors printed, and if not select "Gears" demo and try running it. Check if you see the 3D colorful gears spinning and report back.

**Comment by DroWnThePoor** [comment]
GTK-4 Demo opens, and I get this in the active shell:

```
[📦 com.github.rafostar.Clapper ~]$ gtk4-demo
** Message: 02:12:03.873: For syntax highlighting, install the “highlight” program
Gsk-Message: 02:12:03.910: Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkX11Toplevel': No available configurations for the given pixel format
```
Then Gears:
![image](https://user-images.githubusercontent.com/16339020/127967071-b25e6299-516b-4277-9313-886827eb4084.png)

Do you have a guess on the approximate issue?
I'm on 18.04 Gnome 3.28, but it's Flatkpak so it's a bit confusing.
I am also about a month behind on system updates, but on purpose though.

**Comment by Rafostar** [comment]
> Do you have a guess on the approximate issue?
> I'm on 18.04 Gnome 3.28, but it's Flatkpak so it's a bit confusing.

So its a GTK4 issue. In order to be able to use Clapper which uses GTK4 you need to make GTK4 work on its own first. This looks like a problem with your GPU driver. I don't have a Nvidia GPU, but from what I know I guess you also need a corresponding to your host Nvidia driver in the form of flatpak package installed. Your system (Ubuntu 18.04) also seems quite ancient, there is 20.04 available for quite some time now.

I know that there is work on the GTK side to improve Nvidia support recently, dunno if it applies to your problem through. You can ask about this non-working `gtk4-demo` on GTK matrix channel, to see if its fixed already, otherwise you can open them an issue on GTK gitlab. Since this isn't a Clapper issue, there is nothing that I can do about it here, unfortunately.

**Comment by shvargon** [comment]
@Rafostar I faced the same problem. And yes gtk4-demo gives the same error, only the problem is in the enviroment settings of flatpak. To be more precise, the GST_PLUGIN_SYSTEM_PATH set in the flatpak. I rewrote it globally and clapper worked.

```bash
shvargon@asustuf:~$ cat /var/lib/flatpak/overrides/global 
[Environment]
GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0
```

Although this can be done without globally rewriting like this
```bash
shvargon@asustuf:/var/lib/flatpak/overrides$ sudo flatpak override --env=GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0 com.github.rafostar.Clapper
```

I took it from the data of another package like this

```bash
shvargon@asustuf:~$ flatpak run --command=sh org.gnome.Builder 
[📦 org.gnome.Builder ~]$ cat /.flatpak-info 
[Application]
name=org.gnome.Builder
runtime=runtime/org.gnome.Sdk/x86_64/41

[Instance]
instance-id=1789458962
...
[Environment]
...
GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0
...
```

But in fact, this is a calculated variable mk Builder initially does not change this enviroment

```bash
shvargon@asustuf:~$ flatpak info -M org.gnome.Builder
[Context]
shared=network;ipc;
sockets=x11;wayland;session-bus;system-bus;fallback-x11;ssh-auth;

...

[Environment]
G_SLICE=always-malloc
```
Maybe you shouldn't override it in flatpak?

sorry my bad english autotranslate.

**Comment by Rafostar** [comment]
> To be more precise, the GST_PLUGIN_SYSTEM_PATH set in the flatpak. I rewrote it globally and clapper worked.

We need to change this for now, as we must build whole gstreamer with plugins, as the one in Flatpak is still too old then we require.

Having this env fix "gears" in gtk4-demo seems very unlikely as this isn't GTK4 env and gears demo does not use gstreamer at all. And the GL renderer that fails is part of GTK4, not gstreamer. It failed at GTK4 before we even start to try to open gstreamer playback. Maybe its something else that you also changed?

**Comment by shvargon** [comment]
> > To be more precise, the GST_PLUGIN_SYSTEM_PATH set in the flatpak. I rewrote it globally and clapper worked.
> 
> We need to change this for now, as we must build whole gstreamer with plugins, as the one in Flatpak is still too old then we require.
> 
> Having this env fix "gears" in gtk4-demo seems very unlikely as this isn't GTK4 env and gears demo does not use gstreamer at all. And the GL renderer that fails is part of GTK4, not gstreamer. It failed at GTK4 before we even start to try to open gstreamer playback. Maybe its something else that you also changed?

Yes, I apologize, I gave out not fully verified information.
I removed the enviroment rewriting by returning the values ​​set by clapper and the error did not appear again, but I was able to repeat it now exactly.
Looked at the history of bash, it turns out I did something else there.
It was so when I saw that the enviroment is different, I tried to change it, but I don’t know the exact command and while I was trying to figure out how which command works, I entered the command

```bash
flatpak update
```

This command suggested to me to install
org.freedesktop.Platform.GL.default 20.08 and 21.08 (as it turns out it's Mesa) and I thought that it was just updates that were falling and gave her permission.
Now to confirm that these packages are missing, I removed them

```bash
flatpak remove org.freedesktop.Platform.GL.default
```

And the error returned immediately after I repeated the first command and he immediately offered me to put mesa again. By the way, for reference, I just put flatpak yesterday. Ubuntu 21.10 system nvidia 470.86 driver first I installed gnome builder from an interesting one, he brought me nvidia-470-86 with me (in the host system the same version of drivers is installed by the way flatpak himself can see it as that) and openh264. And then he put clapper.

So sorry I was wrong, it wasn't about the environment.
PS: By the way, here are screenshots of what the error looks like and how it works
![Снимок экрана от 2021-12-30 00-42-12](https://user-images.githubusercontent.com/4750220/147684655-4e4ef1ef-c0e0-423a-a2e0-2560b3635979.png)
![Снимок экрана от 2021-12-30 00-41-50](https://user-images.githubusercontent.com/4750220/147684841-131c0171-ffe2-4179-8dca-0ff1c2f1b9f9.png)

**Comment by shvargon** [comment]
@Rafostar By the way, what is interesting when updating, he writes what he puts:


org.freedesktop.Platform.GL.default 20.08 and 21.08


It was only through flatpak list that I realized that it was Mesa. Well, in order to make it clearer, here's a screenshot.


![Снимок экрана от 2021-12-30 00-49-56](https://user-images.githubusercontent.com/4750220/147685462-86bf1197-e311-437b-9129-c27295326d1b.png)


But no matter how strange it is, even though gtk4-demo throws errors, it nevertheless launches the demo video player gtk4 widget and even plays


![Снимок экрана от 2021-12-30 00-56-08](https://user-images.githubusercontent.com/4750220/147685909-1b0bc7f4-6c1c-4a3f-a989-8c7e0e26513a.png)

**Comment by Rafostar** [comment]
@shvargon 

First of all, if you have changed default `GST_PLUGIN_SYSTEM_PATH`, app gonna start mixing plugins build against older and newer GStreamer versions and cause all sort of issues. Please restore it to what Clapper was using.

I think `org.freedesktop.Platform.GL.default` should be automatically preinstalled on first time install of any app from Flathub. There are alternatives of this one like 32bit version, mesa-git etc. so we should not make an explicit dependency of it.

> Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkX11Toplevel': No available configurations for the given pixel format

When you get such error, then OpenGL rendering in GTK4 failed. In such case gtk4 will quietly switch to software rendering instead of using GPU accelerated one (software rendering = very bad performance).

You can check what renderer is used with:
```sh
GTK_DEBUG=interactive flatpak run com.github.rafostar.Clapper
```
Global->Information should say NGL, otherwise it will say Cairo for software renderer.

**Comment by shvargon** [comment]
@Rafostar Yes I have already removed the enviroment changes. In fact, to confirm the error, I cleared all the packages and tried to repeat my actions again. That's what I did:


![Снимок экрана от 2021-12-30 12-20-59](https://user-images.githubusercontent.com/4750220/147721578-0ec1d01a-d943-4ca5-ad65-dc3496ab39fa.png)

Then I run clapper:


![Снимок экрана от 2021-12-30 12-21-34](https://user-images.githubusercontent.com/4750220/147721611-f23e04b8-d427-49ef-b260-2753f090c388.png)

And as you can see, I could not repeat the mistake. But nevertheless, flatpak did not install mesa at the first installation, which is why I had an error. I don’t know what it’s connected with, but one thing remains the exact problem, apparently, in flatpak and its incomprehensible behavior during the first installation, at least on my system. Well, in any case, if such errors occur, it is worth looking at whether mesa is installed.
