### ISSUE TITLE
Enable building in Builder

### ISSUE THREAD

**Issue by bertob** [Rafostar/clapper#12]
For drive-by contributions it's very useful to be able to build projects with a single click in GNOME Builder. I think all you need to do for that is include the Flatpak manifest in the repo itself.

**Comment by Rafostar** [comment]
> include the Flatpak manifest in the repo itself.

It is in `pkgs/flatpak` folder. Everything I made related to this project is publicly available.

**Comment by bertob** [comment]
Huh, then I don't understand why Builder doesn't build it. Does it work for you?

**Comment by Rafostar** [comment]
To tell the truth, right now I am on Fedora Silverblue and I am doing all this experimenting with app and custom GStreamer patches inside a toolbox container. Since the GUI is put together in GJS I can immediately test every change without compiling. As for Flatpak building, to make my life easier I made a single script that builds, does GPG signing, generates static-deltas, tags it with git commit and pushes to hosted repo.

Nevertheless, I will check why Builder fails.

**Comment by Rafostar** [comment]
@bertob 

I can edit and run the app from inside the Builder just fine. It compiles locally using `meson` and not as Flatpak through. The `Export Bundle` button is grayed out (insensitive). I do not know why, cause Builder says it has `Errors 0` and `Warnings 0`.

Also saw this after searching in web a little. Possibly because I have the manifest written in `yml`:
[https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/520](https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/520)

**Comment by bertob** [comment]
Dunno, it's not being recognized here (Builder stable and nightly, Fedora 33):

![image](https://user-images.githubusercontent.com/1908896/99964804-3145cd80-2d94-11eb-9386-8ea62685de4d.png)

**Comment by Rafostar** [comment]
I converted the manifest to JSON format in the latest commit. After this building Flatpak from GNOME Builder started working for me. So I think it should be OK now.

First time compile takes quite a while through. There is a LOT of dependencies (mostly video codecs) to compile after all.

**Comment by bertob** [comment]
Works now!
