### ISSUE TITLE
Use dark style by default

### ISSUE THREAD

**Issue by bertob** [Rafostar/clapper#13]
As a general rule, media-heavy apps (such as video or photo apps) use Adwaita dark, in order to highlight the content.

**Comment by Rafostar** [comment]
By default, I prefer to match other windows when windowed (use system theme variant) and go dark, semi-transparent when fullscreen. I will add an option to force dark when windowed in the future. For now, you can start it from terminal like this to force dark theme:
```sh
GTK_THEME=Adwaita:dark flatpak run com.github.rafostar.Clapper
```

The progress bar gets a little too dark through. I will have to improve that before adding dark theme option.

**Comment by bertob** [comment]
> By default, I prefered to match other windows when windowed (use system theme variant) 

That's not how Adwaita is intended to be used. If your system stylesheet is anything other than regular Adwaita some apps are going to break, have illegible text, etc. Adwaita dark exists for media apps (like this one) to choose to use explicitly, not as something to use at the system level.

If and when there's a global prefer-dark setting this may change, but even then media apps would still be light in normal mode.

**Comment by Rafostar** [comment]
> some apps are going to break

Celluloid (previously gnome-mpv) uses dark theme as an option for years and I have not seen anyone complaining:
[https://github.com/celluloid-player/celluloid/blob/33658af2e4d666c58da03fe0f449968c6c0220cd/data/io.github.celluloid_player.Celluloid.gschema.xml#L21](https://github.com/celluloid-player/celluloid/blob/33658af2e4d666c58da03fe0f449968c6c0220cd/data/io.github.celluloid_player.Celluloid.gschema.xml#L21)

**Comment by Rafostar** [comment]
> Adwaita dark exists for media apps (like this one) to choose to use explicitly

You are the designer here. So I will trust your word and follow the guidelines to set the dark theme for media apps as default.

**Comment by bertob** [comment]
> Celluloid (previously gnome-mpv) uses dark theme

Right, that's what i meant. Apps that are designed to be dark dark obviously don't break, it's only when someone forces dark on apps that weren't meant for it that you get issues, because nobody tested it :)

**Comment by sp1ritCS** [comment]
> So I will trust your word and follow the guidelines to set the dark theme for media apps as default.

Please let them be switchable, because there are a lot of "dark-only" apps, and I don't like that I cant change them to light mode.

**Comment by bertob** [comment]
> I don't like that I cant change them to light mode

Why? What's the use case for a light video player?

**Comment by Rafostar** [comment]
It might be just my monitor, but for me `dark` enabled + `osd` CSS class gives way too dark scale highlight. It looks really bad. On fullscreen it looks like somebody set the scale (in this case the position bar) to being `insensitive` (disabled interactions) and I cannot override the default color, cause that would obviously break custom theming.

The app always used `osd` class which is dark on fullscreen, cause making light fullscreen would indeed be very bad for a movie player and for your (:eye: :eye:) I will make this optional (like Celluloid does), cause for custom themes there is no guarantee anyway if dark variant would work better than the light one and some people prefer light theme.

And due to the "slider is so dark, it looks like it is not sensitive" issue, I will keep it on light by default for the time being (can be changed in prefs). If the dark color scheme on `OSD` in `Adwaita` improves a little bit, I will switch the default to dark.

**Comment by Rafostar** [comment]
Attaching images for comparison (I prefer light in these).

**Adwaita Light:**
![adwaita-light](https://user-images.githubusercontent.com/40623528/99853299-033d6f00-2b83-11eb-8b53-0093265257da.png)

**Adwaita Dark:**
![adwaita-dark](https://user-images.githubusercontent.com/40623528/99853335-151f1200-2b83-11eb-80ee-07bc862e64c0.png)
