### ISSUE TITLE
gsth264decoder.c(460) error - unsupported profile: 66

### ISSUE THREAD

**Issue by juxuanu** [Rafostar/clapper#130]
I am trying to play this video: 

https://user-images.githubusercontent.com/24759034/129516793-182fb84a-5fe8-43c7-a5d8-33d9fd1daf82.mov

But it fails to load.

I have the MR build installed and I `╰─🚀 flatpak run --command=sh --user com.github.rafostar.Clapper` to see this output:
```
╰─🚀 flatpak run --command=sh --user com.github.rafostar.Clapper
[📦 com.github.rafostar.Clapper ~]$ gst-play-1.0 ~/Vídeos/test.mov 
Press 'k' to see a list of keyboard shortcuts.
Now playing /home/icar/Vídeos/test.mov
ERROR Failed to decode data for file:///home/icar/V%C3%ADdeos/test.mov
ERROR debug information: ../gst-libs/gst/codecs/gsth264decoder.c(460): gst_h264_decoder_handle_frame (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstVaH264Dec:vah264dec0
Reached end of play list.
```

It plays fine with my local GStreamer:
gstreamer 1.18.4-1 (same version for codecs)

**Comment by Rafostar** [comment]
This is a _Baseline_ video (profile 66, normally unsupported by VAAPI) that needs to be handled as _ConstrainedBaseline_ in order to make it work with hardware acceleration. Doing it like this is done in `gstreamer-vaapi` implementation, but not yet in newer `va` that are used by default in the "custom" build that you are using.

There is already an open MR on the gstreamer gitlab to address this: [gst-plugins-bad/-/merge_requests/2428](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/2428)

Since there is already a "fix" for this prepared in the gstreamer and there is nothing to do here, I am gonna close this.

**Comment by Rafostar** [comment]
In case someone else stumbles upon this issue: The required change is now backported as a patch into Flatpak version, so its another option to get this working until merged upstream.

**Comment by juxuanu** [comment]
This was just merged.

**Comment by Rafostar** [comment]
Good. This means that next GStreamer release is sure to have it (backporting to flatpak is still needed until then), and that people running gstreamer-git packages or using Flatpak Nightly should also get this working.
