### ISSUE TITLE
0.4.0 does not follow system theme

### ISSUE THREAD

**Issue by Rmdhn1** [Rafostar/clapper#159]
why

**Comment by Rafostar** [comment]
Latest version uses lib called "libadwaita". We are basically forced to use that lib if we want to have fancy and mobile friendly preferences window and other adaptive widgets etc. The thing is that lib automatically enforces Adwaita theme on startup. Apperantely GNOME developers decided that apps do not deserve custom stylesheets support. I hate that too, but it's not my fault and there is nothing I can do about it here. ALL other apps once updated to GTK4 + libadwaita combo will have that problem.

**Comment by Rafostar** [comment]
Upstream issue: [https://gitlab.gnome.org/GNOME/libadwaita/-/issues/215](https://gitlab.gnome.org/GNOME/libadwaita/-/issues/215)

**Comment by sp1ritCS** [comment]
considered patching that update_theme function in libadw for flatpak users?

**Comment by Rafostar** [comment]
> considered patching that update_theme function in libadw for flatpak users?

I wish it was that simple, but doing so would simply break all Adw widgets (including prefs window) due to missing styles. Remembering initial user theme and switching forth and back when prefs window is opened/closed might be a some sort of extreme countermeasure. But honestly I would love to have as little weird workarounds as possible.

**Comment by Rmdhn1** [comment]
huh, looked on the issue and it doesn't look like they're planning to fix it, well then, closing since it's libadwaita
