### ISSUE TITLE
Feature Request: Option to enqueue new files

### ISSUE THREAD

**Issue by CharoSW** [Rafostar/clapper#165]
Rather than replacing the current playlist when opening a new file it would be nice if there was an option to just send it to the bottom of the queue

**Comment by Rafostar** [comment]
@CharoSW 

Hold left `Ctrl` button when dropping file(s) onto the player from file manager. But due to [https://github.com/Rafostar/clapper/issues/75](https://github.com/Rafostar/clapper/issues/75), flatpak version still has some limitations as mentioned in that conversation.

**Comment by Rafostar** [comment]
Above seems easy to use. As one can select, open multiple files from file manager (e.g. Nautilus) and append more files for playback with D&D while holding `Ctrl` key or replace playlist without holding it. This cannot be added as an checkmark option to current file chooser window in player, as its using system-provided native file choosing. Otherwise it would require adding another file chooser implementation for such use-case with another main menu option. I would rather not bloat GUI with too many options.

If you agree, lets close this.

**Comment by CharoSW** [comment]
That is almost my issue but not quite.  The effect of queuing the media if it's in xdg-videos is what i was looking for and it's unfortunate that the flatpak version has that limitation, but there is also an additional aspect to what i was meaning.  I normally open files by double clicking them or using the context menus of the file manager (in most cases Nautilus).  Doing that always wipes the current playlist and replaces it (although you can still use the normal ctrl and shift methods to replace the playlist with multiple files).  Being that this isn't a D&D I don't know if it would be subject to the same access limitations as that other bug.  The files i was trying to play do open fine after just double cllicking them, though not with D&D

**Comment by Rafostar** [comment]
> I normally open files by double clicking them or using the context menus of the file manager (...) Being that this isn't a D&D I don't know if it would be subject to the same access limitations

Um, I am not sure what you are requesting for at this point. Nautilus default double click action is "Open" and it should as name say open that file, not queue it. D&D does not work yet because fix needs to happen in Nautilus, not here. If you want another "Add to Clapper playlist" right click menu option in file manager, someone would need to write such script/extension for Nautilus.

> They're on an external hdd if that makes much difference

To fix D&D, you might be able to manually grant application additional permissions to some specific directory with something like:
```sh
flatpak override com.github.rafostar.Clapper --filesystem=/path/to/your/hdd
```

For additional right click menu option as mentioned earlier, this would need a custom user-made extension for Nautilus (it supports extensions), but this would need to happen as separate project and not here.

**Comment by CharoSW** [comment]
To use VLC as an example it has an option where when you open the file using the file manager it can just add it to the bottom of the queue and keep the current piece of media playing.  Thus you don't need to drag and drop to add files to the playlist, just open them from the file manager as you would normally.  Celluloid also has a similar option, although for various reasons of my own I would prefer to not use either of those two.  Here is a screenshot of VLC's option
![Screenshot from 2021-09-29 23-42-18](https://user-images.githubusercontent.com/19259975/135280839-6752d109-3184-44d9-8499-79485e6417dc.png)

Worth noting that at least in Celluloids case this isn't the default action nor would I expect it to be the default here either, when most people "open" a media file their expected behavior is probably to have it play.  Also, if this hasn't quite cleared up what I mean I can see if i can put together a proof of concept patch, JS isn't a language i am great at but it could be worth me diving into th deep end

**Comment by Rafostar** [comment]
@CharoSW 

Hmm. Making it as a not default option configurable in preferences seems like plausible solution to me. Will be added, but I have some pending playlist functionality reworking/rewriting, so after that is done.
