### ISSUE TITLE
Round bottom corners

### ISSUE THREAD

**Issue by bertob** [Rafostar/clapper#17]
With GTK4 (and HdyWindow in GTK3) we're moving to rounded bottom corners on all windows.

I don't know what exactly you need to do to get it in this case, in theory it should come automatically if you use the latest GTK, but not sure.

**Comment by Rafostar** [comment]
> it should come automatically if you use the latest GTK

Yes. It will change automatically once new version of `GTK4` is available. The version with that change is not available yet, and I would rather wait until it is tagged as new stable release instead of building it from latest git.

**Comment by Rafostar** [comment]
Due to the app design changes to better match upcoming GNOME 40, app will automatically have rounded bottom corners when used with Adwaita theme.

@bertob I am doing the rounded headerbar-less app window with OSD buttons on top of video like in your GNOME videos app mockups (cause I really liked them). Since this OSD headerbar buttons idea comes from your mockups, let me know if you want me to add you to the credits in app "About" dialog. Thanks.

Here is a screenshot of what I am talking about from the upcoming app version:
![screenshot-windowed](https://user-images.githubusercontent.com/40623528/108543976-1aa50900-72e6-11eb-86a4-1c2342f5c4e9.png)

**Comment by bertob** [comment]
No need to credit me, but happy to hear about the round corners!

By the way, the two connected buttons next to the primary menu look a bit weird because there's so much more space between the icons than around them. I'd either increase the size/padding overall, or add some kind of divider, to make the horizontal spacing more even. Alternatively you could also just split them up again, and have them be independent circles.

**Comment by Rafostar** [comment]
> I'd either increase the size/padding overall, or add some kind of divider

Thank you for your advice. I will go with the divider then.

**Comment by Rafostar** [comment]
Corners of the video window are now automatically rounded. The rest of the app windows/dialogs will be rounded if rounded corners are part of the user used theme. Nothing more to do here, so closing.
