### ISSUE TITLE
Feature Request: Playback speed upto 3x

### ISSUE THREAD

**Issue by NusryNizam** [Rafostar/clapper#178]
Hi there.
Currently, the playback speed is limited up until 2x. Would it be possible to increase upto 3x?
Thanks.

**Comment by crepererum** [comment]
Can this be reconsidered? I'm often watching YouTube videos in high res in the browser at 3x speed and my laptop handles this just fine (requires an extension because YouTube also locks the maximum to 2x). While I agree that certain setups might have problems with this, I think that many users have beefy enough setups to handle this.
