### ISSUE TITLE
yt-dlp support

### ISSUE THREAD

**Issue by mossymossmoss** [Rafostar/clapper#179]
yt-dlp (https://github.com/yt-dlp/yt-dlp) is a fork of youtube-dl with additional features. It would be nice to have a way to use it in clapper. Perhaps the ability to install it as a flatpak plugin or to be able to give a custom path for the youtube-dl excecutable

**Comment by Rafostar** [comment]
This issue description is very lacking. For what purpose you want to have yt-dlp support in the first place? Why do you want to run additional executables like youtube-dl from the main app process? What are you trying to achieve?

**Comment by MossyMossMoss** [comment]
Sorry for lack of detail. Upon doing some more research, it appears that MPV has switched to using yt-dlp by default in all future releases. This means that Clapper will get support for yt-dlp upon thenext release where it uses the new MPV version. 👍

**Comment by Rafostar** [comment]
> Sorry for lack of detail. Upon doing some more research, it appears that MPV has switched to using yt-dlp by default in all future releases. This means that Clapper will get support for yt-dlp upon thenext release where it uses the new MPV version.

Except that Clapper does not use MPV at all. It uses GStreamer, thus my questions about why you need yt-dlp support remain.

**Comment by VarLad** [comment]
@Rafostar How does Clapper play Youtube videos?

I think it implements its own stuff for playing youtube vidoes?

**Comment by Rafostar** [comment]
> How does Clapper play Youtube videos?
> I think it implements its own stuff for playing youtube videos?

Yes. I have my own stuff to achieve that. I still do not know for what purpose OP wanted to have `yt-dlp` (no reply), but if this is only due to recent YT new throttling mechanism, then this was already taken care of. The current YT code will be removed and replaced with a custom lib (optional dependency) that I am recently working on to play well with our GStreamer backend. Although support for it is not merged into clapper git master yet.

**Comment by MossyMossMoss** [comment]
The throttling was my biggest issue. Apologies for the confusion, I was under the false assumption that Clapper used MPV. Good to know that you are working on a custom lib that should fix this issue

**Comment by Midar** [comment]
I think the main idea here is that there is already a project that keeps up with YouTube changes so that the reverse engineering work does not need to be duplicated. This project used to be youtube-dl but in recent times has become yt-dlp due to upstream inactivity. I think it would make sense to allow using yt-dlp, as it can just return the URLs to its caller that can then be fed to gstreamer. Or maybe there could even be a gstramer transport that uses yt-dlp? Letting yt-dlp do the actual downloading has the advantage that is tries to act as "normal" as possible to YouTube.

**Comment by Rafostar** [comment]
After debating about it for a while, the final decision is to make player 100% free and independent of such external web scrapers. This is gonna be left to GStreamer modularity and available plugins entirely (i.e. if you want to use yt-dlp, find/make a gstreamer plugin that works with yt-dlp and so on).

In case of Flatpak version I am including (since Clapper 0.4.1) my own new lib (that I was working on recently) and a GStreamer plugin that uses it. Because this is new and I cannot remove stuff for a patch release, ATM this code path that uses that lib can be enabled with `GST_PLUGIN_FEATURE_RANK=gtubersrc:300` env. Otherwise old code will be used. In the near future, old (and broken) Clapper youtube code is gonna be removed entirely in favor of using user provided GStreamer plugins for handling such "extra" features.

But neither yt-dlp or even my own lib are NOT gonna be implemented as part of Clapper media player. I am giving freedom for anyone to make/use whatever he/she wants to achieve desired result. My own lib is included in Flatpak package to provide something that works "out of the box". That's all on this matter.
