### ISSUE TITLE
Pause video on left click

### ISSUE THREAD

**Issue by bertob** [Rafostar/clapper#18]
It'd be cool to pause/play the video when clicking anywhere on the video.

**Comment by Rafostar** [comment]
It was always available, but with right button. This way I can avoid video stutter when entering fullscreen with double click, which would otherwise cause pause on first click and both unpause and fullscreen on second click (hence the stutter).

**Comment by bertob** [comment]
Hmm, right click is not very intuitive for this, so I don't think that's a good substitute.

How about having a slight delay before actually pausing, and cancelling it if/when the second click comes?

**Comment by Rafostar** [comment]
> How about having a slight delay before actually pausing, and cancelling it if/when the second click comes?

Do-able, but it would involve quite a bit of additional program logic. Especially since left button is also used for dragging the player window (even when clicked on video) which makes the experience much more enjoyable on touchscreen display. So app would have to distinguish these 3 outcomes.

**Comment by demolg** [comment]
@Rafostar please reconsider `left click to pause`. Video is paused when I click to focus window that makes me annoyed

**Comment by Rafostar** [comment]
@demolg There is no ideal solution here unfortunately. Otherwise there would be no right click context menu and without that menu, no option to be always on top. The only tip I can give you currently is that clicking on top title header will not pause the player when you focus. Alternatively you can click and drag window a tiny bit to avoid pausing.

**Comment by afdia** [comment]
Hi, I really love the simplicity and low resource consumption of the player, but I think this behavior is unexpected (MPV pauses on right click, VLC doesnt pause at any click)

I often have 2 windows open: browser left and video right (50/50 size)
Most of the time I'm using the browser, but if I want to skip a part of the video, I have to focus it first (and stop it unintentionally by clicking). The same happens if I open another window which overlaps the video partially; I click on the video to bring it to the foreground and it stops.

It would be nice if this behavior could be configurable in the future (via UI or maybe only via config file). Anyway, thanks for the great player!

**Comment by Rafostar** [comment]
@afdia 

> I often have 2 windows open: browser left and video right

And for this reason right click context menu was assigned to right click - so you can use it like that and select always on top easily. In your use-case left click seems useful actually, cause video can stay on top then and you can enjoy browsing net (with browser maximized) while having video in corner.

> It would be nice if this behavior could be configurable in the future (via UI or maybe only via config file).

The best that could be done it would be to have an option in preferences to simply disable toggle play on left click. Well, ideally we should not have too many options in preferences window :man_shrugging: but if we assign it back to right click, we lose context menu...

And then comes another problem of whether this translates into touch-only devices or not, cause right now we pause on left click or screen tap... But what on touchscreen desktop? Tap to change window focus also does toggle play then which could be deemed wrong, but what about mobile touchscreen (phone)? In this case tap to pause is probably always desired.

**Comment by afdia** [comment]
"Always on top" unfortunately doesn't help, because I need to focus the video if I want to use keyboard shortcuts (e.g. arrow to skip 10sec)

Currently I use the middle mouse button to focus as workaround or just click another time to resume the video.

I agree that left click pause is probably the best default for touch devices and that right click is problematic with the context menu.

It's also clear that too many options cause visual clutter, but maybe the existing shortcut overview could be extended to allow reassigning shortcuts in future versions? Maybe change "Left mouse button" to a dropdown with Left, Right, None? Just an idea :)
