### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by gavr123456789** [Rafostar/clapper#19]
System: arch, builded from AUR  
After start I see this:  
![image](https://user-images.githubusercontent.com/30507409/100087204-6834e580-2e5f-11eb-8fc6-40ca255408a6.png)

**Comment by Rafostar** [comment]
ping @sp1ritCS 
I think that your PKG in AUR is using latest git from master. Even through it was supposed to be outdated `GTK3` build, which is probably not what people want either. Could you temporary remove it from AUR until we are ready to ship `GTK4` version?

As for your issue @gavr123456789 I am very sorry to disappoint you, but this player is using quite a few "bleeding edge" technologies that are not upstreamed in `GStreamer` yet. One of them is `gtk4glsink` plugin that I prepared especially for this media player - first error tells you it is missing from your system. All what is needed is included as patches in Flatpak build, otherwise you would have to rebuild some `GStreamer` plugins using some of the patches found in this repo until they accept my merge requests for `GStreamer`. I really do recommend you to go with Flatpak on Wayland session for the time being.

**Comment by sp1ritCS** [comment]
Removing packages from AUR is not possible. (A maintainer can only abandon them)

May you push a legacy version that works with gtk3 to a sperate branch?

**Comment by Rafostar** [comment]
@sp1ritCS 

Can it be set to build from specific commit maybe? This is the last commit that happened before `GTK4`:
[https://github.com/Rafostar/clapper/commit/e7e9b9c07d884c1d412b15f0069117ddc7d0e635](https://github.com/Rafostar/clapper/commit/e7e9b9c07d884c1d412b15f0069117ddc7d0e635)

Also flagging it as outdated would be good.

**Comment by sp1ritCS** [comment]
> Can it be set to build from specific commit maybe?

yes, submitted it to aur and as pull here

---

> Also flagging it as outdated would be good.

Flagging as outdated for vcs packages is only if upstream changed to build procedure or upstream's location changed.
