### ISSUE TITLE
Librem 5: The link on about page does not work

### ISSUE THREAD

**Issue by carlosgonz0** [Rafostar/clapper#195]
Tested on Librem 5 then the clapper link on about page do  not work.

**Comment by Rafostar** [comment]
This is handled by about dialog which is part of GTK4, so it would not be mine bug, but I do not think its a bug, simply something missing in your system configuration.

From what I know you need to have any web browser installed first and additionally set in system settings that browser as "default application" for opening Web links.

**Comment by carlosgonz0** [comment]
Yes i have a browser the Epiphany and set in system  as "default application" for opening Web links.

**Comment by carlosgonz0** [comment]
I tested with other flatpak app like Mousai i same issue it happen i can not open the link on about page.

**Comment by Rafostar** [comment]
@carlosgonz0 

> Mousai i same issue

I do not own a Librem 5, so I am not sure if/what is missing or needs to be configured on the device to make this work. Clearly not a Clapper bug since you have the same problem with other apps.

Probably would be best if you could ask for help other mobile Linux users on some community forums or something to get help with this one. Closing as its not something that can be fixed inside Clapper.
