### ISSUE TITLE
NVIDIA: Glitches in playback

### ISSUE THREAD

**Issue by zakaria-chahboun** [Rafostar/clapper#200]
I have the latest version 0.4.1, and NVIDIA 470.86
![image](https://user-images.githubusercontent.com/18173275/149366585-f6d0af4f-c40b-4441-a693-8b9d5494c6c5.png)

**Comment by Rafostar** [comment]
> I have the latest version 0.4.1, and NVIDIA 470.86

Flatpak ver or not?

**Comment by Rafostar** [comment]
I have seen this happen on multi GPU setups (integrated Intel + NVIDIA), where both VAAPI and NVDEC are being registered and hardware might end up with using wrong API with wrong device (e.g. VAAPI with NVIDIA GPU). Please tell if you happen to be running such setup.

If this is Flatpak version, please check if you have both mesa and the same nvidia drivers also installed as a flatpak packages. Also for starters, check the name of used video decoder (can be found in first video popover next to progress slider).

**Comment by zakaria-chahboun** [comment]
@Rafostar 
Yes, I have mesa and nvidia from flatpak
My distro is pop!_os, so it's came with these libs by default.
The glitch doesn't happen in the first time, Just after the updating of the app + the flatpak runtimes.

#### Flatpak list (screenshot)
![image](https://user-images.githubusercontent.com/18173275/149963689-8c69a450-587d-429c-8d3b-86f8caaf5184.png)

#### Video decoder (screenshot)
![image](https://user-images.githubusercontent.com/18173275/149964510-7e45d15f-2463-4695-afd5-9b7f953216cb.png)

**Comment by Rafostar** [comment]
@zakaria-chahboun 

> The glitch doesn't happen in the first time, Just after the updating of the app + the flatpak runtimes.

Yeah, this is the situation I described above earlier. Due to some updates (driver mismatch maybe), app stopped recognizing your NVIDIA GPU and mistakenly tries to use `vah264dec` with VAAPI as you also seem to have Intel/AMD GPU integrated. This causes corruption as the NVIDIA GPU is the one driving the display and GTK GL context.

First and foremost you need to get gstreamer to recognize and register NVDEC decoders. You need to alter your installation (since you mentioned this worked before doing updates) so below command shows more then 0 features in output:
```sh
flatpak run --command=sh com.github.rafostar.Clapper
gst-inspect-1.0 nvcodec
```

Sometimes after doing flatpak updates/reinstalls, removing old cache file might help (as decoders will be retested again) by removing `~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0/registry.x86_64.bin` file.

**Comment by zakaria-chahboun** [comment]
@Rafostar 
Yes it's solved after removing the `gstreamer` cashe.
Thanks!
