### ISSUE TITLE
AV1 videos freeze system every time. Cold reboot necessary.

### ISSUE THREAD

**Issue by 38github** [Rafostar/clapper#224]
Version: Latest flatpak.
OS: Fedora 35 GNOME amd64.
X11, NVIDIA 390.147

**Comment by Rafostar** [comment]
AV1 format is very, very new and requires a lot of up-to-date libraries. There is an ongoing work on the GStreamer side to improve it. Can you temporarily replace your Clapper install with latest git actions nightly build to check if issue is still relevant with latest software?

Link to nightlies: https://github.com/Rafostar/clapper/actions/workflows/flatpak-nightly.yml

**Comment by 38github** [comment]
The nightly fixed the crash and now the video plays. It is very slow though like in the earlier days when dav1d wasn't fully optimized.

**Comment by Rafostar** [comment]
Currently available AV1 decoders are av1dec which uses AOM. We have also VA/VAAPI hardware accelerated decoders if you have new enough Intel/AMD GPU. For Nvidia NVDEC AV1 support is not yet merged (if your Nvidia GPU can hw accel it).

A dav1d based decoder for gstreamer exists but it's not included in the Flatpak builds because it's in their Rust repo which we do not build. Maybe it's worth considering it.

**Comment by Rafostar** [comment]
@38github 

> The nightly fixed the crash and now the video plays. It is very slow though

Today's Nightly now includes `dav1d` based decoder. Can you check if it makes any noticeable difference in performance?

**Comment by 38github** [comment]
Great! Thank you but the playback is some what choppy still. Is it using dav1d by default? Btw, does the zipped flatpak files take much less space than if they were not compressed with zip? If no then it would be one less step to go through to install them.

**Comment by sp1ritCS** [comment]
> Btw, does the zipped flatpak files take much less space than if they were not compressed with zip? If no then it would be one less step to go through to install them.

AFAIK all github build artifacts pushed by [actions/upload-artifact](https://github.com/actions/upload-artifact) are automatically zip files. There is no way around using it. Surprisingly a single zip with a file in it is quite simple, if you want to push a folder with lots of small files, you tend to have a zip with another archive in it, because gh zip algo takes ages to go recursivity  through dirs.

**Comment by Rafostar** [comment]
> Great! Thank you but the playback is some what choppy still. Is it using dav1d by default? Btw, does the zipped flatpak files take much less space than if they were not compressed with zip? If no then it would be one less step to go through to install them.

Check the name of the used decoder in the first popup button to the right of progress slider. Should say `rsdav1ddec` in this case. Files are automatically zipped, unzipping should not be a problem here.

**Comment by 38github** [comment]
> rsdav1ddec

Yes, it does say that. Now Clapper doesn't freeze the system but it is not as smooth playing as for example MPV.
