### ISSUE TITLE
Ending time calculation is wrong when speed != 100%

### ISSUE THREAD

**Issue by Midar** [Rafostar/clapper#225]
The ending time is always calculated assuming a speed of 100%. The formula should instead use `now + (seconds_total - seconds_elapsed) * speed)`

**Comment by Rafostar** [comment]
This is now partially fixed with: https://github.com/Rafostar/clapper/commit/c94d21fc533540147cefd56a515f70c427619295

Leaving this open because its still not ideal as we do not track playback rate changes, thus value does not get updated immediately when speed slider is moved (only when OSD is reshown or refreshed via other means).

**Comment by Rafostar** [comment]
New app UI aims at simplicity and consistency among windowed, fullscreen and mobile view. For this reason clock had to be removed in it, thus this issue is no longer applicable - closing.
