### ISSUE TITLE
[Non clapper bug (i think)] playbin3 - Webm quick open

### ISSUE THREAD

**Issue by BirdInFire** [Rafostar/clapper#233]
i push this bug to add to the https://github.com/Rafostar/clapper/issues/35,

When i use the experimental playbin 3 (on fedora 35 with nvidia's drivers), on wayland gnome.
Replicated on a laptop (fedora 35 with intel graphics) on wayland.

What happen ?
When i open a webm file, open a second one (who replace the first one), and reopen the first, the picture go black (but the sound continue and clapper work normally (just black picture).

This behavior does not when playbin3 is disabled it's possible that is a cache issue (because the bug only happen when i try to reopen a webm video already opened during the clapper's session.

**Comment by Rafostar** [comment]
I mainly keep that list of non-clapper issues only to track the progress of merge requests I did to fix them and in order to have a few noted that are not possible to fix or workaround here but have an upstream issue reported and linked. Also to let people know which ones might be fixed in Flatpak version of the app (my MRs were included as a patch, but now a lot of that got merged upstream).

GStreamer has its own issue tracker on their gitlab, no point writing every GStreamer issue here, if its not mine issue to fix. Especially if said issue only happens with an option that I clearly marked as experimental.

Also I tried last Clapper stable Flatpak + Wayland + playbin3 + local 2 webm videos. A `vp8dec` decoder was used, and I did not reproduce this issue. Although I run on AMD, but should not matter as this was reproduceable on Intel too.

**Comment by BirdInFire** [comment]
> I mainly keep that list of non-clapper issues only to track the progress of merge requests I did to fix them and in order to have a few noted that are not possible to fix or workaround here but have an upstream issue reported and linked. Also to let people know which ones might be fixed in Flatpak version of the app (my MRs were included as a patch, but now a lot of that got merged upstream).
> 
> GStreamer has its own issue tracker on their gitlab, no point writing every GStreamer issue here, if its not mine issue to fix. Especially if said issue only happens with an option that I clearly marked as experimental.
> 
> Also I tried last Clapper stable Flatpak + Wayland + playbin3 + local 2 webm videos. A `vp8dec` decoder was used, and I did not reproduce this issue. Although I run on AMD, but should not matter as this was reproduceable on Intel too.

i know i reported it only to see if it was me only (i do not use playbin3 as daily use), will check later to see the codec used in the webm video (to see what cause the problem), to report it to the true cause of the bug (i don't think it's a clapper issue) but if listed if someone else find the same problem, they not have to report.
