### ISSUE TITLE
Feature Request: Report HW capabilities in About -> System Info

### ISSUE THREAD

**Issue by nullr0ute** [Rafostar/clapper#242]
It would be useful to have a report of HW capabilities in the about system dialog. It would make it easier to verify if Clapper detects and will make use of HW offload engines like the v4l2 stateless codecs

**Comment by Rafostar** [comment]
> if Clapper detects and will make use of HW offload engines like the v4l2 stateless codecs

This part is already present and visible if you open video track selection popover (next to progress slider), same goes for used audio decoder. I might add an additional dialog with more video info (like current bitrate, etc.) eventually.

**Comment by Rafostar** [comment]
Also in addition to video/audio popovers which show currently used decoder name (so whenever we use HW accel and which one) there is also a plugin ranking in prefs which shows a list of all available decoders. You should be able to open `v4l2codecs` tab there to see which of those decoders are currently registered (available).

The whole decoders list is kinda long as we have a lot of both software and hardware accelerated elements there. It does not seem necessary to duplicate all that in system info dialog. Especially since having decoder detected does not mean that it will be used, as either some other decoder for the same format might have higher rank and it will be used instead, video resolution exceeds what HW decoding supports, color depth is too high, etc. So we have info which decoder is used right now (what users are really interested in) in the video/audio track selection popovers.

As I mentioned earlier I might add a dialog with additional video file info, but it does not seem to be what you are asking for here.

**Comment by Rafostar** [comment]
Whenever Software or Hardware decoder is used (and its name), will be shown in new "Info" dialog/window.

> I might add an additional dialog with more video info (like current bitrate, etc.) eventually.

This is now also added in WIP libclapper branch.
