### ISSUE TITLE
pipewire audio is unbalanced towards left headphone

### ISSUE THREAD

**Issue by legacychimera247** [Rafostar/clapper#244]
hello, player works great, but if i select the experimental pipewire audio, i notice that i can clearly hear the sound is coming more from the left headphone than the right, and this does not happen with pipewire disabled, where the sound is perfectly balanced, couldn't try with my speakers, but i will also try those

don't really understand this issue as i am on fedora 35 workstation so i should be using pipewire already, but anyway, reporting it since it may be helpful

just in case, clapper is in rpm, coming from your repo

**Comment by Rafostar** [comment]
Options that are marked experimental are well... experimental, because there are known issues with PipeWire GStreamer implementation (like sometimes crashing on seek, etc.) that is why I marked them as experimental.

> don't really understand this issue as i am on fedora 35 workstation so i should be using pipewire already, but anyway, reporting it since it may be helpful

The difference is that when disabled sound will go through `pipewire-pulse` module, like any other app targeting PulseAudio before PipeWire existed. With this option enabled in Clapper will simply use `pipewiresink` element for audio sink and sound will go directly to PipeWire server on your host (skipping `pipewire-pulse` middle-ware).

So you should be fine using the default (disabled) option. In any case we use `pipewiresink` "as is" (which is a part of PipeWire). If there are any problems with it, then assuming its not a fault of your system configuration, any problems with it should be reported on PipeWire gitlab instead of here. Since nothing about it can de done here, closing.

**Comment by legacychimera247** [comment]
i know it's experimental, i just thought to report it for completeness, and yes, my config should be the defaulf configuration, anyway i will consider report it to the pipewire team
