### ISSUE TITLE
Time to cut a new release?

### ISSUE THREAD

**Issue by 1player** [Rafostar/clapper#260]
Latest release is from December, looks like there's been some work and bug fixes since which haven't been released yet.

**Comment by Rafostar** [comment]
One MAJOR change that I was working on since last release is the brand new video sink. It was merged recently, gives slight performance improvement on capable HW, prepares initial support for more platforms (like Windows and macOS) and is ready for implementing other optimizations and requested by users features that are going to be gradually added.

I do plan to do a release that contains both old and new sink for smoother transition (i.e: if there is a problem with new one its still possible to use the old). Still waiting for one GTK4 issue to be resolved first, so mobile linux users won't hit problems on PinePhones.

Also, I kindly ask you to consider using other means for asking questions then issue tracker. Its getting messy, when its used for both reporting issues and some questions about development. For this purpose please consider using [Clapper matrix channel](https://matrix.to/#/#clapper-player:matrix.org) (preferred method) or if you can't/don't want to set account there for some reason, please at least use GitHub discussions feature then. Thank you for understanding.
