### ISSUE TITLE
Enhancements to PiP mode

### ISSUE THREAD

**Issue by kdwk** [Rafostar/clapper#266]
The Picture-in-Picture mode offered by Clapper could use the following enhancements to be even more useful:

1. When entering PiP mode, automatically shrink to a predefined size and place the shrunken window in a corner of the desktop
2. When entering PiP mode, automatically set 'always on top' and 'always on visible workspace' to true
3. When in PiP mode, lock the height and width ratio of the window to that of the video so the video always take up the entirety of the window
4. When hovering cursor over PiP window, show some sort of overlay buttons to play/ pause video and skip 5 seconds forward/ backward
5. When exiting PiP mode, automatically enlarge window to previous size
6. When exiting PiP mode, automatically set 'always on top' and 'always on visible workspace' to previous values (may _not_ be false)

I believe these improvements would users to watch a video alongside whatever they are doing more easily and comfortably.

**Comment by Rafostar** [comment]
> 1, 5

Why do we want a resizing on its own window here? Seems annoying to me, and would break the neat controls hiding animation.

> 2, 6

This one is a limitation of Wayland. It was working with older GNOME Shell version by talking to Mutter over DBus, but GNOME devs disabled this functionality, so we work around it with an extension that does just that: https://extensions.gnome.org/extension/4691/pip-on-top/

**Comment by Rafostar** [comment]
@gargullia I do not maintain Arch packages (especially extension). Might be extension packaging issue. Make sure you enabled said extension after installing. And please **do not** use someone else feature request to start your own issue discussion.

**Comment by Rafostar** [comment]
There is no more of a dedicated "floating/PIP mode". Currently app is always "floating" since its now all OSD. Ability to have it always on top is left to the right click context menu, which now opens with a right click anywhere on video. In this menu you can select manually `always on top` and/or `always on visible workspace` to your liking.

As long as your DE provides an option there, it will work. All my own hacks targeting GNOME were removed, since they were broken for a long time now. For this reason, closing.
