### ISSUE TITLE
[Flatpak] Distorted, laggy, green-tinted video output

### ISSUE THREAD

**Issue by 1player** [Rafostar/clapper#286]
![image](https://user-images.githubusercontent.com/690120/175807255-6aaad7b1-c2c4-4e95-b827-9e108ec93d9b.png)

Doesn't affect Celluloid nor Totem, both installed from Flathub.

Fedora Silverblue 36 with `ffmpeg-libs` but no other non-free media libraries layered.

Output of `ffmpeg -i` for this video file:

```
Input #0, matroska,webm, from 'Videos/Forbidden Siren/Let's Play SIREN p.1 - Zero O' Clock [4Dnr4_4Ykyg].webm':
  Metadata:
    ENCODER         : Lavf59.16.100
  Duration: 00:14:26.64, start: -0.007000, bitrate: 855 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:14:26.565000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:14:26.641000000
```

**Comment by Rafostar** [comment]
AMD GPU? Also please provide all mesa flatpak packages versions you have installed.

**Comment by 1player** [comment]
AMD Radeon RX 6800 XT (sienna_cichlid, LLVM 14.0.0, DRM 3.46, 5.18.5-200.fc36.x86_64)

On the host: mesa 22.1.1

On flatpak:

```
% flatpak list | grep GL
Mesa    org.freedesktop.Platform.GL.default     21.3.8  21.08   flathub system
Mesa git snapshot       org.freedesktop.Platform.GL.mesa-git    22.1-branchpoint        21.08   flathub-beta    user
default org.freedesktop.Platform.GL32.default           21.08   flathub system
Mesa git snapshot       org.freedesktop.Platform.GL32.mesa-git  22.1-branchpoint        21.08   flathub-beta    user```

**Comment by Rafostar** [comment]
@1player 

So my guess was right. Because you forced `mesa-git` everywhere you have run into this AMD mesa regression: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6491

It is fixed in latest mesa main, but flatpak mesa-git package even if it is called "git", it not really updated on a daily basis from latest git main branch. Running all Flatpak apps with mesa-git is not really recommended, unless you feel adventurous. Please consider applying the ENV only to the Flatpaks that really need it (like Steam). Then Clapper will use stable `21.3.8` version you have that does not have this problem. Or wait till the fix eventually reaches that so called "git" mesa package.

**Comment by 1player** [comment]
My bad, I actually thought that environment variable was only used by the Steam wrapper, and would not affect anything else, while in fact you're saying that all Flatpaks now are using mesa-git, which isn't ideal. 

In my case I pinned a stable mesa version (the 22.1 stable) to avoid running broken versions, so I would not have gotten the updates you mention anyway.

Since this is a user problem with a weird, unsupported configuration, I'll close the issue. Thanks for the help!
