### ISSUE TITLE
[Flatpak] Move to Gnome 43 platform

### ISSUE THREAD

**Issue by BirdInFire** [Rafostar/clapper#315]
Hope to see an update to move from org.gnome.Platform/x86_64/42 to org.gnome.Platform/x86_64/43 before Fedora 37 land with gnome 43 on it.

Thanks for this software !

**Comment by Rafostar** [comment]
Due to Fedora 37 and now also latest Flatpak runtime disabling hardware acceleration of h264 and HEVC because of patents concerns, changing runtime is currently put on hold, at least until this situation is resolved. Ongoing discussion about reenabling it in Flatpak apps can be found here: [https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1494](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1494)

**Comment by Rafostar** [comment]
AFAIK, at least in case of Flatpak with 42 runtime, mesa that works with it is at ver 21 (Flatpak apps use its own mesa, not the one from distro) which is unaffected. That is why I am keeping it like this for the time being. Since I do not know how they will handle reenabling it, I am waiting until this discussion is resolved before updating.

**Comment by maymage** [comment]
The above mentioned [issue]( https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1494) has be resolved.

**Comment by Rafostar** [comment]
> The above mentioned [issue](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1494) has be resolved.

Yes, and GNOME runtime also recently updated itself with added mesa-extra changes, so there is nothing stopping us now.

**Comment by Rafostar** [comment]
Updated to 43 on Flathub. Update should appear soon.
