### ISSUE TITLE
Add Slovak language for translation

### ISSUE THREAD

**Issue by tj314** [Rafostar/clapper#331]
I would like to translate the app into Slovak (sk.po). Could you add the language to Crowdin? Thank you.

**Comment by Rafostar** [comment]
I added Slovak language and accepted your join request. Currently the github CI is broken, so your eventual translation will not appear (be merged) immediately, but it shouldn't prevent you from translating slowly on Crowdin in your free time. Should be fixed in next few days. Thanks for contributing.

**Comment by Rafostar** [comment]
Your Slovak translation is now included in latest git. Latest Flatpak builds in github actions page should now also contain it. Thanks for translating.
