### ISSUE TITLE
Feature Request: Option to show file name instead of metadata

### ISSUE THREAD

**Issue by lisiczka43** [Rafostar/clapper#358]
It seems to display the name of a video stream in matroska files, which often contains language tags or other garbage information when no file title is present, making it difficult to navigate playlists. Thanks.

**Comment by Rafostar** [comment]
As a first step, we should improve parsing of videos to not use audio track title when no others are present as a whole media title.

**Comment by lisiczka43** [comment]
That's great if you're aware of the issue and working on it. I also have a small suggestion for subtitles rendering and will update the appropriate opened issue.

**Comment by Rafostar** [comment]
This should be now improved. Player will only show video container title (without fallback to audio track name). And if none, it should simply display file basename without extension. I do not think we need to add custom preferences for this. Would be to much clutter. Since I hope this is improved in latest git, I am closing this. If you try latest code and disagree (still have problem) feel free to reopen.
