### ISSUE TITLE
Get current state over websocket without performing action?

### ISSUE THREAD

**Issue by peteruithoven** [Rafostar/clapper#363]
I'm trying to make a very simple remote website using the websocket that I could use from my phone to control Clapper on my laptop.
When the websites opens I'd like to know the current state of Clapper, whether it's playing or paused. I receive this state when sending [actions](https://github.com/Rafostar/clapper/blob/master/src/player.js/#L360-L396) like `toggle_play`, but there doesn't seem to be a way to receive the state without altering the playback? 

Current code: https://stackblitz.com/edit/js-uiw7vp?file=index.js

**Comment by Rafostar** [comment]
Hi, the WebSocket server functionality is going to be changed slightly as part of undergoing Clapper code rewrite.

First of all you will be able to do a `GET` request anytime at `http://$IP:$PORT` to receive JSON data with all current values like requested in this issue.

Second, the WS messages syntax is going to be changed. Sorry. Since I do not want to write my own JSON parser nor have a build dependency on an external library just for this feature of video player, as now I am dealing with C code only and not JavaScript, so JSON is harder to read. With that, the previous message send to control the player:
```js
JSON.stringify({ action: 'play' })
```
is now going to be simply:
```
play
```
Additional arguments will be separated with whitespaces, eg. to add video:
```
add https://example.com/video
```

Third, client is going to receive current playback position changes, speed, volume, etc. via WebSocket messages with same syntax as above, eg:
```
volume 0.86
```
There will also be a `queue_changed` messages meaning some data in playback queue (upon which new Clapper operates got changed). In this case after receiving such message, client can fetch JSON data again to update its UI accordingly with new queue (new items, video titles, etc.).

I do hope to finally write some documentation with all possible actions, their descriptions and how to use this WebSocket communication overall after this reworked implementation is merged.

**Comment by Rafostar** [comment]
Should probably mention it here, but now Clapper uses dynamic port + MDNS to announce it. This is to allow multiple instances (or maybe even some other app that uses Clapper API) on single computer:

For example, using AVAHI:
```sh
avahi-browse -r _clapper._tcp -t
```

**Comment by peteruithoven** [comment]
But, while I appreciate it supporting multiple instances, this means a simple webservice hosted somewhere else than Clapper can't figure out this port? We'd need a helper or browser extension on the same machine/LAN to figure out the port? 
(Note that the port seems to change every time Clapper is rebooted.)


Looking at the `--help` I can't propose a port when starting Clapper from the command line?

**Comment by Rafostar** [comment]
Depends on what/how you are trying to achieve. For example Node.js has wonderful `multicast-dns` module that can find (and list) all Clapper instances running in your house.

You cannot force port, since we now do multiple windows and then each window gets a different port.

**Comment by peteruithoven** [comment]
That's a fair point, it all depends on the use-case. 

It seemed like `bonjour-service` was quite a bit simpler to use than `multicast-dns`. A simple example: 
``` js
// Use bonjour-service for mDNS/Bonjour discovery
import { Bonjour } from 'bonjour-service'

const bonjour = new Bonjour();

const browser = bonjour.find({ type: 'clapper', protocol: 'tcp' });
// const browser = bonjour.find(); // find all

browser.on('up', service => {
  const {name, type, host, port} = service;
  console.log(`up: ${name} (${type} @ ${host}:${port}`);
});

console.log('Searching for Clapper services on the local network...');
```

I did notice, that when opening multiple windows it didn't always find the clapper services. I'll open a separate issue.
