### ISSUE TITLE
Opus audio at half rate 

### ISSUE THREAD

**Issue by lorenzo0932** [Rafostar/clapper#366]
Some file with opus audio play at half hz rate causing poor audio quality. 
File tested:
![immagine](https://github.com/Rafostar/clapper/assets/60674575/49661812-732f-45c7-b193-0a76c470cdc2)

I used pw-top for check if something was wrong and this is what i've found:
![Schermata del 2023-07-05 16-37-06](https://github.com/Rafostar/clapper/assets/60674575/762cd73f-9af5-42bc-bf32-8bb78fe8a8e3)

I tried with mpv and this is what i found:
![immagine](https://github.com/Rafostar/clapper/assets/60674575/d8e70a78-d152-4b3c-835e-66cda2d315c0)

There is no difference in using pipewire experimental setting.

**Comment by Rafostar** [comment]
Does this also happen with:
```sh
gst-play-1.0 video.mp4
```

**Comment by lorenzo0932** [comment]
> 

yes, same problem

**Comment by Rafostar** [comment]
This seems to be limitation of `opusdec` element from GStreamer. See: https://gstreamer.freedesktop.org/documentation/opus/opusdec.html#src. Dunno if this is caused by used lib or GStreamer implementation limitation, but if the latter, then a feature request on GStreamer gitlab instead would be more appropriate place.

Alternatively `avdec_opus` from libav can output more formats on its src pad. See: https://gstreamer.freedesktop.org/documentation/libav/avdec_opus.html?gi-language=c#src

You can enforce the usage of this one in Clapper preferences -> Tweaks -> plugin ranking, by enabling rank override of `avdec_opus` element under `libav` and setting a high value to it (e.g. 300). Player restart is required after changes there. You can confirm which one is used during playback when you open an audio track selection popover button.

**Comment by lorenzo0932** [comment]
> This seems to be limitation of `opusdec` element from GStreamer. See: https://gstreamer.freedesktop.org/documentation/opus/opusdec.html#src. Dunno if this is caused by used lib or GStreamer implementation limitation, but if the latter, then a feature request on GStreamer gitlab instead would be more appropriate place.
> 
> Alternatively `avdec_opus` from libav can output more formats on its src pad. See: https://gstreamer.freedesktop.org/documentation/libav/avdec_opus.html?gi-language=c#src
> 
> You can enforce the usage of this one in Clapper preferences -> Tweaks -> plugin ranking, by enabling rank override of `avdec_opus` element under `libav` and setting a high value to it (e.g. 300). Player restart is required after changes there. You can confirm which one is used during playback when you open an audio track selection popover button.

for me this is working maybe i open a issue on gstreamer gitlab.
But anyway why not using avdec_opus instead of opusdec by default?

**Comment by Rafostar** [comment]
>  But anyway why not using avdec_opus instead of opusdec by default?

I do not change these ranks (for most elements at least). I provide an option to manually edit them by user in preferences. We go with what GStreamer devs decided here.

If you open the docs pages I sent you earlier, you will see that `opusdec` is rank "primary" by default while `avdec_opus` is "marginal", meaning that `opusdec` will be preferred by default if installed. `avdec_opus` comes from ffmpeg libav, so its basically the same decoder that `mpv` uses since `mpv` is based on `libav`/`ffmpeg`.

You would have to ask GStreamer devs why they decided to go with different lib by default in this case, considering it can (at least currently) output only S16LE.

**Comment by lorenzo0932** [comment]
> > But anyway why not using avdec_opus instead of opusdec by default?
> 
> I do not change these ranks (for most elements at least). I provide an option to manually edit them by user in preferences. We go with what GStreamer devs decided here.
> 
> If you open the docs pages I sent you earlier, you will see that `opusdec` is rank "primary" by default while `avdec_opus` is "marginal", meaning that `opusdec` will be preferred by default if installed. `avdec_opus` comes from ffmpeg libav, so its basically the same decoder that `mpv` uses since `mpv` is based on `libav`/`ffmpeg`.
> 
> You would have to ask GStreamer devs why they decided to go with different lib by default in this case, considering it can (at least currently) output only S16LE.

ok thank you so much for the explanation and for your help :+1:
