### ISSUE TITLE
Playback issue with Intel Arc series GPU

### ISSUE THREAD

**Issue by wolf-yuan-6115** [Rafostar/clapper#369]
I'm using Intel Arc GPU with Fedora Workstation 38, when I trying to play video, weird artifices appeared:

VP9 Video: 
![image](https://github.com/Rafostar/clapper/assets/58245644/a9c6c2bc-898b-4ea6-a4be-11e13864b87e)

AV1 Video:
![image](https://github.com/Rafostar/clapper/assets/58245644/739281d2-33e1-4182-94ad-3977de17fda9)

## Installed packages:
`dnf list installed | grep intel`
```
intel-gmmlib.x86_64                                  22.3.9-1.fc38                       @updates                                                
intel-gpu-firmware.noarch                            20230625-151.fc38                   @updates                                                
intel-igc.x86_64                                     1.0.13700.7-1.fc38                  @fedora                                                 
intel-igc-libs.x86_64                                1.0.13700.7-1.fc38                  @fedora                                                 
intel-media-driver.x86_64                            23.1.6-1.fc38                       @rpmfusion-nonfree                                      
intel-mediasdk.x86_64                                23.2.2-1.fc38                       @updates                                                
intel-opencl.x86_64                                  23.05.25593.18-1.fc38               @fedora                                                 
intel-opencl-clang.x86_64                            15.0.0-3.fc38                       @fedora                                                 
oneVPL-intel-gpu.x86_64                              23.1.3-2.fc38                       @anaconda                                               
xorg-x11-drv-intel.x86_64                            2.99.917-55.20210115.fc38           @anaconda
```

## System Information:
```
OS: Fedora Workstation 38
CPU: AMD Ryzen 7 7700 (It have an iGPU)
GPU: Intel Arc A750 8G
```

**Comment by wolf-yuan-6115** [comment]
I've encounted similar issue on Waydroid and support group says it's because software is trying to use two GPU at same time, is there a possible fix?

**Comment by Rafostar** [comment]
Is this Clapper Flatpak? If not, please try with Flatpak package.

**Comment by wolf-yuan-6115** [comment]
> Is this Clapper Flatpak? If not, please try with Flatpak package from Flathub.

Yes, I tried both the rpm version and the Flatpak version.

**Comment by wolf-yuan-6115** [comment]
RPM Version:
![image](https://github.com/Rafostar/clapper/assets/58245644/aecbb085-8070-4fd3-918d-31d6ea567af0)

FlatHub (Flatpak) version:
![image](https://github.com/Rafostar/clapper/assets/58245644/8ecf6d07-f912-4d14-9fc1-70cfbfa1cc83)

(Flatpak bottom bar is transparent, though it can't be seen inside screenshot)

**Comment by wolf-yuan-6115** [comment]
For reference, I installed VLC using Flatpak and it played my media correctly.

![image](https://github.com/Rafostar/clapper/assets/58245644/8fb8988f-1dba-4cc2-975f-35e440174d65)

**Comment by Rafostar** [comment]
What you see here is most likely caused by using wrong DRM format modifiers when decoding video. Modern Intel GPUs use these for efficiency when decoding video, but support for them is not yet added to GStreamer (backend that Clapper uses). There is ongoing progress for this to happen soon through.

Here is upstream issue I opened about this some time ago. It also has steps described how to detect the modifier that your GPU uses: [https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1236](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1236)

You can follow what I did in this issue to recomplie (at least GStreamer GL lib) with it from the stable release your system has installed. Since you also have an iGPU, another thing you can try is to use iGPU for decoding. To do this, go to Clapper preferences -> Tweaks -> Plugin ranking -> VA, and find change rank of all the decoder names there with `renderD` to higher value then non-renderD ones. Or wait for upstream to fix this problem, but since its not Clapper fault there is nothing that I can do here.

**Comment by wolf-yuan-6115** [comment]
> What you see here is most likely caused by using wrong DRM format modifiers when decoding video. Modern Intel GPUs use these for efficiency when decoding video, but support for them is not yet added to GStreamer (backend that Clapper uses). There is ongoing progress for this to happen soon through.
> 
> Here is upstream issue I opened about this some time ago. It also has steps described how to detect the modifier that your GPU uses: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1236
> 
> You can follow what I did in this issue to recomplie (at least GStreamer GL lib) with it from the stable release your system has installed. Since you also have an iGPU, another thing you can try is to use iGPU for decoding. To do this, go to Clapper preferences -> Tweaks -> Plugin ranking -> VA, and find change rank of all the decoder names there with `renderD` to higher value then non-renderD ones. Or wait for upstream to fix this problem, but since its not Clapper fault there is nothing that I can do here.

Hello, changing Plugin Ranking did the trick, I can tell it's using my GPU because my iGPU can't even decode 8K@30, `nvtop` also reported it's not using iGPU.

![image](https://github.com/Rafostar/clapper/assets/58245644/27a56357-df49-4969-bf38-30cc23c049df)

**Comment by Rafostar** [comment]
> Hello, changing Plugin Ranking did the trick, I can tell it's using my GPU because my iGPU can't even decode 8K@30, nvtop also reported it's not using iGPU.

Then in your setup iGPU is the primary (first) GPU while Arc is 2nd GPU (with renderD suffix in ranking). We cannot really tell which GPU user prefers for which codec if he has multiple GPUs, so that is why this can be configured in preferences. Upstream issue with modifiers still is valid, but in your case it seems to actually be triggered when using iGPU and not Intel Arc.

> Both VP9 and AV1 plays correctly now.

You can always confirm if you are using HW acceleration and by which element when you open video popover (next to progress slider on the right side). It should say actually used decoder name. And the decoders will be tried as set in preferences (from highest number value).
