### ISSUE TITLE
Shortcut / Key to load next video file from current catalog

### ISSUE THREAD

**Issue by TRVLD** [Rafostar/clapper#396]
Greetings,

I'm searching for a way  (a key or shortcut) that will trigger loading and autoplay of the next supported file from the current catalog.

Alternatively, a functionality similar to 'action when film stops' known from clsid2 / mpc-hc  project, basically when video ends playing, the next video from current catalog is loaded and starts playing, so we have a sequence.

**Is any of these implemented already, or do you know a workaround to get behavior in Clapper?**

Thank you for the info!
BR,
MJ

**Comment by Rafostar** [comment]
Upcoming Clapper version operates on a "playback queue" model. Meaning, you can schedule multiple files for playback, change their order as you please and/or set how they are selected when current one ends (consecutive order, random, etc.).

You will be able to switch between them with media keys from your keyboard. This is basically what you request for here, I think.

But Clapper will NOT browse and read your files on your computer on its own. You will have to add/open multiple files from folder(s) (or online sources) yourself. This would otherwise break whole safety of a Flatpak container. I do not think selecting and opening multiple files or dragging a few into an app window is too much to ask user for.

**Comment by Rafostar** [comment]
As mentioned previously, in latest git there is now possibility to easily add (queue for playback) multiple videos. Shortcuts with a OSD title notification when you switch them have been added to. So this works like requested, except for the fact that you need to open or at least drag and drop files into player yourself. A functionality for the player to freely browse open/read files on user computer will not be implemented, sorry but I am against anything insecure.
