### ISSUE TITLE
Speed up/down keyboard shortcut incorrect?

### ISSUE THREAD

**Issue by peteruithoven** [Rafostar/clapper#418]
The Shortcuts popup says to press <kbd>></kbd> or <kbd><</kbd> to speed up or down, but it also seems to require pressing  <kbd>Shift</kbd>?

**Comment by Rafostar** [comment]
No. It is as it should be. The key is `<` and you need to hold shift to write this said key, otherwise key would be comma (`,`). At least that's what I have on my keyboard :smile:

Writing this shortcut as Shift + comma would be incorrect, as not every keyboard layout has greater/less keys above comma/dot.

**Comment by peteruithoven** [comment]
Ahh so sorry, that makes total sense.
