### ISSUE TITLE
Clapper not working

### ISSUE THREAD

**Issue by YuryenUcahh** [Rafostar/clapper#453]
I using fedora 40 and after updates codecs my clapper not working. I tried mp4 webm and mkv, only mkv working

https://github.com/Rafostar/clapper/assets/51506997/85e923f5-3cf2-4ebc-9091-81f71eab5ef8

I apologize if this problem is not caused by clapper, I don't know much about this kind of issues.

**Comment by Rafostar** [comment]
This is legacy version of Clapper (0.5 ver release), since then Clapper code was completely rewritten for 0.6. Due to that its very hard and not really profitable to try to fix the code that was abandoned 2 years ago. Please update to 0.6.0 and see if the problem persists. Latest stable version can always be found on Flathub as Flatpak package (that I personally maintain) and includes all that should be necessary to work as part of it which is the recommended package to use.

**Comment by YuryenUcahh** [comment]
flatpak version works without any problems thanks for that
I hope the new version will be in the fedora repositories soon, because I need clapper for gnome-hanabi extension

**Comment by Rafostar** [comment]
@YuryenUcahh 

> I hope the new version will be in the fedora repositories soon, because I need clapper for gnome-hanabi extension

Dunno about stable RPM package since I do not maintain that, but if you are fine with experiments (running unstable versions), you can get latest git compiled Fedora packages from my repo, link [here](https://software.opensuse.org//download.html?project=home%3ARafostar&package=clapper)
