### ISSUE TITLE
ERROR: Unknown variable "clapper_possible_features"

### ISSUE THREAD

**Issue by jovi-tsx** [Rafostar/clapper#468]
Trying to install clapper doing step by step correctly but when I run `sudo meson setup builddir`, I receive the error mentioned in the title. My meson version is 1.4.1 and here's the full log file from `clapper/builddir/meson-logs/meson-log.txt`:

[meson-log.txt](https://github.com/user-attachments/files/16041099/meson-log.txt)

**Comment by Rafostar** [comment]
This is caused by clapper API build to be skipped due to unsatisfied dependencies (before variable is declared). Yes, this needs a quick fix, cause it should not error out like that.

On the other hand, until you update your system you will not be able to compile anyway.
TIP: If you cannot update for some reason and just want the player application, you can always use Flatpak package.

**Comment by jovi-tsx** [comment]
My OS version is Pop OS 22.04 Nvidia, so I am using the up-to-date version... I was trying to install hanabi (live wallpapers) and it asked to install clapper: https://github.com/jeffshee/gnome-ext-hanabi/blob/master/docs/ubuntu-22-04.md

**Comment by Rafostar** [comment]
You cannot compile latest git on 22.04 LTS since, even if it is currently latest release of Pop OS it's still an over 2 years old system that unfortunately doesn't ship latest needed dependencies (until 24.04).

You can compile an older Clapper version 0.5.2. But as far as I know Clapper has a Debian package, so you should be able to install it with APT.
