### ISSUE TITLE
Video full color range is displayed as standard range

### ISSUE THREAD

**Issue by Topicranger** [Rafostar/clapper#469]
I recorded a clip using the new Steam Recording feature, but noticed that the colors are wrong.
Firefox, ffplay and mpv-based players display the video correctly.
It seems that the wrong color range is used.

Output:
![output](https://github.com/Rafostar/clapper/assets/43324723/a148660a-93a3-44f3-bb7c-06fae2061ef5)
Expected:
![expected](https://github.com/Rafostar/clapper/assets/43324723/b33dd2be-88f1-4b20-8a96-135864c267c8)

ffprobe output:
Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 1920x1080, 11948 kb/s, 60.02 fps, 1000k tbr, 1000k tbn (default)

Additional Details:
OS: bazzite (Fedora Silverblue 40)
Compositor: Wayland
GPU: NVIDIA RTX 4070

**Comment by Rafostar** [comment]
So since you use silverblue this when using Clapper Flatpak, yes? What is the name of video decoder used (from "i" window)?

**Comment by Topicranger** [comment]
Yes. The decoder used is nvh264dec.

**Comment by Rafostar** [comment]
GL texture and colorspace conversion is done in GStreamer (especially in Nvidia case), so here is reported upstream issue: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1260

It needs to be implemented/fixed there. Clapper does nothing wrong on this part here. Since we have found upstream issue, closing.
