### ISSUE TITLE
Chromecast / screen streaming

### ISSUE THREAD

**Issue by tabzlock** [Rafostar/clapper#47]
Having an option to be able to steam to chrome cast or other screen streaming services would be great. The only other media player I know that has this option is VLC and it would be really good feature to have on a gtk based media player.

**Comment by Rafostar** [comment]
I am not planning on getting Chromecast into video player anytime soon. Sorry. I have already more than enough work maintaining GNOME Shell extension that does that: [https://github.com/Rafostar/gnome-shell-extension-cast-to-tv](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv).

Video players should do what they are called, play videos. What is the player supposed to show in its window when casting anyway? Black screen? Frozen frame? Whats the point of that window anyway? This seriously doesn't seem like a feature that video player should have, that's why I made a gnome shell extension that does that some time ago.

Casting with a right click from Nautilus seems like a much better solution to me than starting whole video player (and all its underlying libs) that will remain unused during cast.

**Comment by tabzlock** [comment]
I was unaware of your extension but it looks very cool. Thanks for the response I will close the issue now.
