### ISSUE TITLE
[Feature Request] Allow importing external subtitle (.srt) files 

### ISSUE THREAD

**Issue by yasharjit** [Rafostar/clapper#65]
AFAIK, clapper currently does not have a feature where the user can import external subtitle (.srt) files. It would be nice to have.

**Comment by Rafostar** [comment]
@yasharjit 

AFAIK, this was done 2 days ago. Read this commit message for possible ways of opening external subtitles: [https://github.com/Rafostar/clapper/commit/b15b94fc9079b7e52132e0f81195e97ab3e32689](https://github.com/Rafostar/clapper/commit/b15b94fc9079b7e52132e0f81195e97ab3e32689)

**Comment by yasharjit** [comment]
Oh, didn't see that commit. Sorry for the noise.

**Comment by BarbzYHOOL** [comment]
@Rafostar 
I'm on 0.5.2 from flatpak

- these methods must be written in the program itself, not having to spend 15 min to find this
- drag and drop doesn't load the subtitle (or it doesn't show up)
- the video should remember the subtitle and we should be able to keep it, remove it or change it imo
- if opening both the video and the subtitle, it could load them both? dunno if possible
- default subtitle was ultra tiny for me, dunno if it's because it's a video made from a mobile or not

Also, not related but could you add an option in settings to automatically resume without prompt?

**Comment by Rafostar** [comment]
@BarbzYHOOL 
There are some problems related to loading external subtitles currently. I hope to get them fixed as part of a bigger update that is yet to come. I kindly ask you to not use someone else closed issue to start a discussion (especially for multiple topics). For asking questions I advise to use Clapper matrix channel or github discussions feature. Thanks.

**Comment by BarbzYHOOL** [comment]
well i had to look it up on the web to find how to load subtitles so i figured it'd be better to write here because I thought the feature was missing
