### ISSUE TITLE
[Adaptive Support] Preferences dialog doesn't adapt

### ISSUE THREAD

**Issue by alexpattyn** [Rafostar/clapper#67]
# Issue
So far the video player itself works great on the [QEMU image of PureOS](https://developer.puri.sm/Librem5/Development_Environment/Boards/qemu.html) (by extension the librem 5 and pinephone). However, the preference menu does bleed over the screen. Which makes it difficult to use in portrait mode.

## Main Player
![image](https://user-images.githubusercontent.com/28536677/114760126-00f3d100-9d2d-11eb-8a88-e23feac8f14f.png)

## Preferences Menu
![image](https://user-images.githubusercontent.com/28536677/114760364-3993aa80-9d2d-11eb-99e5-cad19608501e.png)

## Example of the preference menu from lollypop
![image](https://user-images.githubusercontent.com/28536677/114760766-adce4e00-9d2d-11eb-888f-ff52fd14ad53.png)

**Comment by Rafostar** [comment]
> So far the video player itself works great on the QEMU image of PureOS (by extension the librem 5 and pinephone).

Had a few people with both an actual Librem 5 and Pinephone, so I know that it supposedly works on actual hardware too. Next GStreamer release should also sort out hardware accelerated playback for those devices, but that is irrelevant to your issue :-)

The preferences (and other dialogs too) are scheduled to be redone using `libadwaita`. They will adopt properly then, but the issue is that `libadwaita` does not have a stable release yet. I am offering other packages besides Flatpak now and I do not want to force anyone into one format or have some dependencies required that cannot be satisfied by package manager. I will redo it into being adaptive as soon as `libadwaita` is out. Please understand.

**Comment by alexpattyn** [comment]
No problem! Thanks for planning ahead on that and its completely understandable to wait for a stable release of `libadwaita`! Looking forward to that release :smiley:.

**Comment by Rafostar** [comment]
Now adaptive:

![Screenshot from 2021-08-23 18-38-47](https://user-images.githubusercontent.com/40623528/130484712-b00b8332-717c-414b-9068-65a32bcf310c.png)
