### ISSUE TITLE
Clapper crash and restart when choosing other subtitle other than default [Flatpak]

### ISSUE THREAD

**Issue by thegarlynch** [Rafostar/clapper#72]
Environment :
Wayland, Flatpak, Gnome, Void Linux

Here are Debug Message :

(com.github.rafostar.Clapper:2): Clapper-CRITICAL **: 01:56:16.373: Error from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstMatroskaDemux:matroskademux0: GStreamer encountered a general stream error.
Internal data stream error.
../gst/matroska/matroska-demux.c(5858): gst_matroska_demux_loop (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstMatroskaDemux:matroskademux0:
streaming stopped, reason not-negotiated (-4)

Also, i tried using DEBUG=Clapper, it works fine

unless in debugging mode it restart

**Comment by Rafostar** [comment]
@thegarlynch 

The error actually says from where this error comes from ;-) But it does not seem like matroska issue, more like old VAAPI plugins issue. What GPU are you on? What sort of video codec are we talking about here?

**Comment by Rafostar** [comment]
The "real" debugging mode is controlled by `GST_DEBUG` env. The `DEBUG` just enables some very simple text logging from GJS code and does nothing more. I highly doubt enabling it can avoid the issue (are you sure?) and if it really does then this makes it some sort of a racy condition. I don't have a Nvidia GPU at hand to test. Please report it on GStreamer gitlab since this really seems like its their issue.
