### ISSUE TITLE
Closing another window with Ctrl+Q sometimes also closes Clapper

### ISSUE THREAD

**Issue by ranchester2** [Rafostar/clapper#78]
I would think this would be already reported, but I couldn't find it.

I am using the Flatpak from Flathub on Debian 11 with GNOME 3.38 and NVIDIA

Basically, I open a video (or just Clapper without one), then I maybe open another window from another app. Then some of the time, when I close the other window, Clapper also closes. There is no error message.

Seems to happen usually if after I close the other window, focus shifts to Clapper. However it doesn't seem to happen 100% of time.

**Comment by Rafostar** [comment]
How do you close that other window? There was a bug that caused closing another window with keyboard shortcuts (Ctrl + Q) to also close Clapper. Is that what you are experiencing perhaps?

**Comment by ranchester2** [comment]
Now I checked closing with the close buttons instead a few times, and I couldn't really get it to happen. (Didn't notice that since I always close with keyboard shortcuts, never with mouse)

So then it is probably that bug. If "there *was* a bug", then I assume its fixed somewhere already and this should be closed? (However I can't seem to find a closed or open issue about it here though)

**Comment by Rafostar** [comment]
> (However I can't seem to find a closed or open issue about it here though)

Nobody reported an issue :-)

> So then it is probably that bug. If "there was a bug", then I assume its fixed somewhere already and this should be closed?

The keyboard shortcuts implementation was redone in at some point in git. It is now improved (with more shortcuts added) and this, with other issues that it caused should not happen anymore. There were too many related code changes, so I cannot backport it into 0.2.X easily.

I will close this, since it should be fixed in git and from 0.3.0 release that will hopefully happen soon. If you still experience it then, please reopen.
