### ISSUE TITLE
PinePhone: Bizarre color corruption with GSK_RENDERER=ngl

### ISSUE THREAD

**Issue by CCF100** [Rafostar/clapper#95]
If I enable the next-gen OpenGL renderer, the UI's colors become corrupted:
https://i.imgur.com/8L4yrBV.png

Env vars used:
```
GSK_RENDERER=ngl LD_LIBRARY_PATH=/usr/local/lib GST_GL_API=gles2 GST_CLAPPER_USE_PLAYBIN3=1 com.github.rafostar.Clapper
```
I took the environment variables from this site: https://briandaniels.me/2021/07/06/hardware-accelerated-video-playback-on-the-pinephone-with-clapper.html

Running on Arch Linux ARM on a PinePhone
Not sure if this is a Clapper issue or a GTK one, but decided to report here first
Oh, one more thing, I installed clapper from this AUR package: https://aur.archlinux.org/packages/clapper-git/

**Comment by Rafostar** [comment]
@CCF100 

Not a Clapper issue. This is a `lima` driver (what PinePhone uses) issue that was already recently fixed in Mesa. You have to wait for the Mesa update.

For more details see relevant issue reported against GTK4: [https://gitlab.gnome.org/GNOME/gtk/-/issues/3894](https://gitlab.gnome.org/GNOME/gtk/-/issues/3894)

**Comment by Rafostar** [comment]
>  Oh, one more thing, I installed clapper from this AUR package: https://aur.archlinux.org/packages/clapper-git/

You can use either clapper git package or compile it yourself, but you still need to have gstreamer 1.19+ for hardware acceleration to work on mobile devices.
