### ISSUE TITLE
Twitch doesnt work

### ISSUE THREAD

**Issue by danrobi11** [Rafostar/clapper#98]
Just tried clapper flatpak and twitch doesnt work.

**Comment by sp1ritCS** [comment]
Who said twitch will work? Clapper doesn't have support for twitch right now.

However, if you have [streamlink](https://github.com/streamlink/streamlink) installed, you can pipe the output from it into Clapper and watch twitch streams like this:
```sh
streamlink twitch.tv/pimpcsgo 720p60 --stdout | com.github.rafostar.Clapper /dev/stdin
```

**Comment by danrobi11** [comment]
@sp1ritCS 

> However, if you have streamlink installed, you can pipe the output from it into Clapper and watch twitch streams.

Yes I does work with `./streamlink-2.2.0-1-cp39-cp39-manylinux2014_x86_64.AppImage https://www.twitch.tv/shroud 480p --stdout | flatpak run com.github.rafostar.Clapper /dev/stdin` Thank you much :) Closing.

**Comment by sp1ritCS** [comment]
might be worth reopening or moving to @Rafostar/gtuber, if supporting twitch is something @Rafostar wants to do

**Comment by danrobi11** [comment]
> might be worth reopening if supporting twitch is something @Rafostar wants to do

Good point.

**Comment by Rafostar** [comment]
Yes, this might be worth eventually adding build-in. For the time being lets leave it here since we do not use that (still unfinished) lib.

Also if you or anyone else has similar problems for any websites (that do not point to video file directly) you can either use piping stdout or using app like `youtube-dl` to get the video/dash link and point clapper to it.

**Comment by sp1ritCS** [comment]
@Rafostar  consider treating "-" as stdin, like other GNU applications.

**Comment by Rafostar** [comment]
> @Rafostar consider treating "-" as stdin, like other GNU applications.

Please open this as separate issue, otherwise its gonna get forgotten/lost.

**Comment by sp1ritCS** [comment]
#100

**Comment by Rafostar** [comment]
Support for all additional websites like Twitch is from now on left entirely to GStreamer plugins (player independent). Latest Clapper Flatpak 0.4.1 includes my own lib + gstreamer plugin for handling few popular websites (including Twitch). ATM, relatively new, experimental and disabled by default. Can be tried with:

```sh
GST_PLUGIN_FEATURE_RANK=gtubersrc:300 flatpak run com.github.rafostar.Clapper
```

If you find other (or have your own) gstreamer plugin for Twitch, you are free to use it instead of mine. Anyway, my point being that this from now on is possible and will be left to gstreamer modularity entirely, instead being part of Clapper.
